language: csharp
mono: none
sudo: required
dotnet: 3.0.100
solution: ./NotesApp.sln
install:
  - sudo apt-get install -qq dotnet-sdk-2.0.0
before_script:
  - chmod -R a+x ./NotesApp/dotnet-build.sh
  - chmod -R a+x ./NotesApp/dotnet-publish.sh
  - chmod -R a+x ./NotesApp/dockerhub-publish.sh
script:
  - ./NotesApp/dotnet-build.sh
  - ./NotesApp/dotnet-publish.sh
  - dotnet test ./Tests
  - ./NotesApp/dockerhub-publish.sh
notifications:
  email:
    on_success: never
    on_failure: never  