version: "3"
services:
  notes-api:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - notes-db
  notes-db:
    container_name: notes-db
    image: microsoft/mssql-server-linux:2017-latest
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Geslo123!"
      ACCEPT_EULA: "Y"